### PR TITLE
Entites, Materials, Inventory

### PR DESCRIPTION
**Pull request by j0ach1mmall3**
Now with partial implementation of certain classes
Why are some commits in there 4 times?

### CODE REVIEW

**Comment by Fireflies** [comment]
>Why are some commits in there 4 times?
That would be due to how you're managing your local repository. Like I recommended earlier it's probably best if you copy the major changes to another directory, fork a clean copy of the `master` branch and apply the necessary changes. Materials for example have been merged into the `master` branch with minor changes.

If you're in need of a git refresher or simple something to consolidate your knowledge then I would recommend reading [Pro Git](http://git-scm.com/book/), as would many sites.

**Comment by j0ach1mmall3** [comment]
Aha, interesting, I'll take a look at it :)

**Comment by nickrobson** [comment]
Squash all of it.

**Comment by j0ach1mmall3** [comment]
Too much commits

**Comment by j0ach1mmall3** [comment]
I will PR a cleaner version soon

**Pull request closed without merging**
