### PR TITLE
Now all in 2 commits

### PR DESCRIPTION
**Pull request by j0ach1mmall3**
Same description as last time.

### CODE REVIEW

**Comment by TheLightMC** [comment]
@j0ach1mmall3 is there any chance we could get the URL to the source you used for ID's?

**Comment by j0ach1mmall3** [comment]
http://minecraft.gamepedia.com/Data_values_(Pocket_Edition)

**Comment by j0ach1mmall3** [comment]
Enchantment IDs are the same as the PC version, I assumed they would be the same since they have the exact same amount.
InventoryType IDs are from the source of PocketMine (https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/inventory/InventoryType.php), but I don't know if it's correct

**Comment by TheLightMC** [comment]
Thanks a ton! I couldn't seem to find that page after I did the original few. Thanks for the contribution, it looks good.

**Comment by nickrobson** [comment]
The InventoryType IDs are kinda bugging me since they're just the same as `#ordinal()` right now.

**Comment by j0ach1mmall3** [comment]
I'm not really sure about them so I'll leave it like this, but if confirmed that they are the same, then I'll remove it.

**Comment by nickrobson** [comment]
Nah, just keep them so they can safely be re-ordered..

**Pull request merged**
